---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nginx-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
  path: ./kubernetes/nell/apps/networking/nginx/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 31m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nginx-external
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-nginx-certificates
  path: ./kubernetes/nell/apps/networking/nginx/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nginx-internal
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-nginx-certificates
  path: ./kubernetes/nell/apps/networking/nginx/internal
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
