apiVersion: v1
kind: Secret
metadata:
    name: probe-1-config
    namespace: oneuptime
stringData:
    PORT: ENC[AES256_GCM,data:FeoRfQ==,iv:9UsdA2dOVZzxKRzrIzprLEB3YymOiiLPcM/r854GQII=,tag:0Xad5Dkh8ls2X2Ujj1+RFQ==,type:str]
    PROBE_NAME: ENC[AES256_GCM,data:COo0le0+qA==,iv:30T8Y35HFg+StnMCaNlctKKyjYNaV5Qk3NSdkfE23E4=,tag:V3hdghFgbEauSfmuBdQntQ==,type:str]
    PROBE_DESCRIPTION: ENC[AES256_GCM,data:J4J2yS1VrowduSBv+WnGuI18dv9qPqY6I/bZ80DC5Oc2KLjbg7E4yWnsXA==,iv:FZxhvhvukNxj0eePca/QJJvwkP4B2wogskJCQGu1eOE=,tag:A+ElfA6Z73j6g1b2OvGDsg==,type:str]
    PROBE_KEY: ENC[AES256_GCM,data:T5Nl4+ccSIc8epblfi+UnPrLJBFQP/oU7Nqy1jtnoPk=,iv:fr1+AoOLOhvIGfTWxUDT4/ppkGcBttaL0GsAHz6RTcU=,tag:Pfdh6uKcxGqE9xEBLb5vmA==,type:str]
    PROBE_API_URL: ENC[AES256_GCM,data:2Id5snCDWbV/RHOL3QghRteR+A+AWnDfa1cRFhVan8N0H+c+r1yRdNhjhg2veZvfGA==,iv:+zsufgbvl9W3MH5ESxyAjncS35GXZnyffw3RU2kJWp4=,tag:9iKd+zYlnFQsvTeZl5uwBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19963x2afvcsek4p5sas5n05thusjvzz7gpfknp20666u69jw44lsu5w4u5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNDJUZk9ObWhZdEJ4SXBB
            V29lYTJuYU1hUlIrWEhIZUE5em9BS2l5VldRCkVvUWlVS082dVNpVEJ1a3BpZlQ1
            QnB3SmJtdWxkVWszWFFocXgrODJTZVEKLS0tIFByU1MrSURWblRLYTI3cS92SEN1
            cExsS1lNQ0RESFVwckhoNU0veThOa3MKcDtsCRQzGPm/KB1RfzjMlzT7rH4k1FK7
            IYGv1q8U2fX6BtWfkuc1W+8mbePnDN7BBgh9K/SiBF6PecKrq5iogQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T23:32:52Z"
    mac: ENC[AES256_GCM,data:gudWOuYZ2SYzjiknDPO1N48/U70EV8AVIGk/m5XbW1hbDdEHBHBt8101An4oIWxO4jqbyaox5suMC5E9PRJi57FCRBSmet9epFJRz6273isO3rVpbqFJmE+/P2peWLXeM/JYP+Jo3F55U0lBYoKHqqzQgRQwPZoYaKT/90xx+3k=,iv:4zINUcrdwiZvLF8n1riE896wjE0EFm7bJrlvAMBPAmg=,tag:uAuTXo29fgyosyodAa6vwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
