---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./secret.sops.yaml
  #- ./externalsecrets.yaml
  - ./helmrelease.yaml
  - ./nodefeaturerule.yaml
commonLabels:
  app.kubernetes.io/name: rtlamr2mqtt
  app.kubernetes.io/instance: rtlamr2mqtt
