---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-prismarine-controller
  namespace: flux-system
spec:
  path: ./kubernetes/apps/prismarine/prismarine-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-prismarine-client
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-prismarine-controller
  path: ./kubernetes/apps/prismarine/prismarine-client
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
