---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: fran-minio
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["fran.outsideour.casa:9002"]
  metricsPath: /minio/v2/metrics/cluster
