---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # Cluster Settings
  TIMEZONE: "America/Los_Angeles"
  CLUSTER_CIDR: "10.98.0.0/16"
  SERVICE_CIDR: "10.99.0.0/16"
  # Static Mappings
  AIRGRADIENT_ADDR: "10.42.42.10"
  KUBE_VIP_ADDR: "10.69.0.2"
