---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: worldserver
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      worldserver:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          worldserver:
            image:
              repository: ghcr.io/kashalls/azeroth-worldserver
              tag: 12@sha256:a0a83c75887d08c9884ccf774d98a8f07b757a0142c62ee3fa85a0765442f219
            env:
              AC_DATA_DIR: "/azerothcore/env/dist/data"
              AC_LOGS_DIR: "/azerothcore/env/dist/logs"
              AC_LOGIN_DATABASE_INFO: "mysql.azeroth.svc.cluster.local;3306;root;password;acore_auth"
              AC_WORLD_DATABASE_INFO: "mysql.azeroth.svc.cluster.local;3306;root;password;acore_world"
              AC_CHARACTER_DATABASE_INFO: "mysql.azeroth.svc.cluster.local;3306;root;password;acore_characters"
              AC_RA_ENABLE: 1
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
            tty: true
            stdin: true
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          imagePullSecrets:
            - name: github
    service:
      worldserver:
        controller: worldserver
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/target: "azwo.ok8.sh"
          io.cilium/lb-ipam-ips: "10.69.0.139"
        ports:
          worldserver:
            port: 8085
          soap:
            port: 7878
          ranet:
            port: 3443
    persistence:
      etc:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2G
        globalMounts:
          - path: /azerothcore/env/dist/etc
      logs:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10G
        globalMounts:
          - path: /azerothcore/env/dist/logs
      client-data:
        existingClaim: dataimport-data
        globalMounts:
          - path: /azerothcore/env/dist/data/
            readOnly: true
