---
roles:
  - src: xanmanning.k3s
    version: v3.2.0
  - src: mabunixda.ansible_udmp
    version: v1.1.0
  - src: sladkoff.ansible_role_grafana_kiosk
collections:
  - name: community.docker
    version: 2.6.0
  - name: community.general
    version: 5.1.1
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.2.2
  - name: ansible.posix
    version: 1.4.0
