---
roles:
  - src: xanmanning.k3s
    version: v3.3.1
  - src: mabunixda.ansible_udmp
    version: v1.1.0
  - src: sladkoff.ansible_role_grafana_kiosk
collections:
  - name: community.docker
    version: 3.4.3
  - name: community.general
    version: 6.5.0
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.6.1
  - name: ansible.posix
    version: 1.5.1
