---
roles:
  - src: xanmanning.k3s
    version: v3.1.1
  - src: mabunixda.ansible_udmp
    version: v1.1.0
collections:
  - name: community.docker
    version: 2.3.0
  - name: community.general
    version: 4.7.0
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.2.1
  - name: ansible.posix
    version: 1.3.0
