---
- name: Setup UDMP
  hosts: udmp
  gather_facts: false
  roles:
    - role: mabunixda.ansible_udmp
      nodeexporter_enabled: on
      # force_external_dns: yes
      # udmp_external_dns_server_ipv4: "192.168.99.100" # e.g. pihole
      # udmp_external_dns_devices:
      #   - br10 # vlan 10
      #   - br20 # vlan 20
