---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rancher/system-upgrade-controller?ref=v0.7.1
images:
  - name: rancher/system-upgrade-controller
    newTag: v0.7.1
