apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - home.yaml
  - metallb-system.yaml
  - networking.yaml
  - storage.yaml
  - monitoring.yaml
  - velero.yaml
  - etc.yaml
